# fly.toml app configuration file

app = 'aestheticsart'
primary_region = 'ord'

[build]

[http]
  [[http.routes]]
    handle = "rewrite"
    match = "/"
    to = "/index.html"

  [[http.routes]]
    handle = "rewrite"
    match = "/pages/*"
    to = "/pages/{path}"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
